correcting typo in the diboson file name under boolean variable isDib…
CMS-PD/ALPHA pull request #160
Opened 2016-10-23 19:58 UTC by SiewYan

…osonInclusive

2016-10-23 21:12 UTC, jpazzini requested changes

2016-10-23 21:12 UTC, jpazzini commented on python/Diboson.py
> +process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(100) )
Please revert back to the previous line (-1 instead of 100 for MaxEvents)

2016-10-23 21:12 UTC, jpazzini commented on python/Diboson.py
> +isDibosonInclusive = (True if (sample=='WW_TuneCUETP8M1_13TeV-pythia8-v1' or sample=='WZ_TuneCUETP8M1_13TeV-pythia8-v1' or sample=='ZZ_TuneCUETP8M1_13TeV-pythia8-v1') else False)
I don't see any changes in the names of the inclusive samples wrt the previous version:

`isDibosonInclusive = (True if (sample=='WW_TuneCUETP8M1_13TeV-pythia8_v1' or sample=='WZ_TuneCUETP8M1_13TeV-pythia8_v1' or sample=='ZZ_TuneCUETP8M1_13TeV-pythia8_v1') else False)`

Please drop also this change

2016-10-25 10:51 UTC, SiewYan commented on python/Diboson.py
> +isDibosonInclusive = (True if (sample=='WW_TuneCUETP8M1_13TeV-pythia8-v1' or sample=='WZ_TuneCUETP8M1_13TeV-pythia8-v1' or sample=='ZZ_TuneCUETP8M1_13TeV-pythia8-v1') else False)
Sorry, i thought the naming convention of MC is similar to all other analysis..

2016-10-25 10:58 UTC, closed without merging